# Site settings
title: Example title
github_username: birkin
description: >
  This is a practice site to demo GitHub Pages.

url: "https://library.brown.edu"

# Build settings
markdown: kramdown
theme: minima
